units:
  # Proxy Spacing Variables
  kx: cx
  ky: cy
  # Padding Variables
  px: kx + 4
  py: ky + 4

points:
  zones:
    main:
      anchor:
        shift: [150, -150]
      key:
        padding: 1ky
        spread: 1kx
      columns:
        outer: 
          key:
            column_net: P18 #F7
        pinkie:
          key:
            column_net: P15 #B1      
        ring:
          key:
            stagger: 12
            column_net: P14 #B3
        middle:
          key:
            stagger: 6
            column_net: P16 #B2
        index:
          key:
            stagger: -5
            column_net: P10 #B6
        inner:
          key:
            column_net: P8 #B4
      rows:
        bottom:
          row_net: P19 #F6
        home:
          row_net: P20 #F5
        top:   
          row_net: P21 #F4
    thumb:
      key:
        padding: 1ky
        spread: 1kx
      anchor:
        ref: main_inner_bottom
        shift: [-25,-20]
      rows:
        cluster:
          row_net: P9 #B5
      columns:
        outer:
          key:
            rotate: 5
            shift: [-4.5]
            column_net: P16 #B2
        middle:
          key:
            rotate: -10
            shift: [1.5,-1]
            column_net: P10 #B6
        inner:      
          key:
            rotate: -25
            shift: [7,-8.5]
            column_net: P8 #B4
   
outlines:
  keys:
    - what: rectangle
      where: true
      size: [kx-0.5,ky-0.5]
  rectangle:
    - what: rectangle
      adjust:
        ref: main_inner_home
        shift: [16.2,-7]
      size: [32.5,70]
      fillet: 2
  board:
    - what: polygon
      operation: stack
      fillet: 2
      points: 
        - ref: main_outer_top
          shift: [-0.5px,0.5px]
        - ref: main_pinkie_top
          shift: [0.5px-4.5,0.5px]
        - ref: main_ring_top
          shift: [-0.5px-0.5,0.5px]
        - ref: main_middle_top
          shift: [-0.5px,0.5px-6]
        - ref: main_middle_top
          shift: [-0.5px, 0.5px]
        - ref: main_middle_top
          shift: [0.5px,0.5px]  
        - ref: main_index_top
          shift: [-0.5px+4,0.5px]
        - ref: main_index_top
          shift: [0.5px,0.5px]
        - ref: main_inner_top
          shift: [0.5px,0.5px]
        - ref: thumb_inner_cluster
          shift: [0.5px,0.5px]
        - ref: thumb_inner_cluster
          shift: [0.5px,-0.5px]
        - ref: thumb_inner_cluster
          shift: [-0.5px,-0.5px]
        - ref: thumb_middle_cluster
          shift: [-0.5px,-0.5px] 
        - ref: thumb_outer_cluster
          shift: [-0.5px,-0.5px] 
        - ref: main_ring_bottom
          shift: [0.5px+1.5,-0.5px]
        - ref: main_pinkie_bottom
          shift: [0.5px,-0.5px+12]
        - ref: main_pinkie_bottom
          shift: [0.5px,-0.5px]
        - ref: main_pinkie_bottom
          shift: [-0.5px,-0.5px]
        - ref: main_outer_bottom
          shift: [-0.5px,-0.5px]
        
  final_board:
    - board
    - rectangle
  
  # Combination preview showing outline and keys.
  combo:
    - name: final_board
    - operation: subtract
      name: keys

pcbs:
  ergoblock:
    template: kicad8
    outlines:
      main:
        outline: final_board
    footprints:
      choc_hotswap:
        what: choc
        where: true
        params:
          keycaps: true
          reverse: true
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode_tht_sod123
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
          reversible: true
          include_traces_vias: true
        adjust:
          shift: [0, -5]
      promicro:
        what: promicro
        where:
          ref: main_inner_top
          shift: [21, -10]
          rotate: -90
      reset:
        what: button
        where:
          ref: main_inner_bottom
          shift: [21,3]
          rotate: -90
        params:
          from: GND
          to: RST
      resetBack:
        what: button
        where:
          ref: main_inner_bottom
          shift: [21,3]
          rotate: -90
        params:
          side: B
          from: GND
          to: RST
      via1:
        what: via
        where: 
          ref: main_inner_bottom
          shift: [24.5,3]
        params: 
          net: GND   
      via2:
        what: via
        where: 
          ref: main_inner_bottom
          shift: [17.5,3]
        params: 
          net: RST              
      trrs:
        what: trrs_pj320a
        where:
          ref: main_inner_bottom
          shift: [30, -10]
          rotate: -90
        params:
          SL: P3  #D0
          R2: GND
          TP: VCC # Tip and Ring 1 are joined together
          reversible: true
          symmetric: true

      


        
